name: ZAP for Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t web-app . && docker run -dp 3000:3000 web-app
    - name: Create test user
      run: |
        curl "http://localhost:3000/api/Users/" \
          --data-binary $'{\"email\":\"test@test.com\",\"password\":\"test1\",\"passwordRepeat\":\"test1\",\"securityQuestion\":{\"id\":2,\"question\":\"Mother\'s maiden name?\",\"createdAt\":\"2022-11-11T13:38:41.754Z\",\"updatedAt\":\"2022-11-11T13:38:41.754Z\"},\"securityAnswer\":\"test\"}'
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:3000'
        cmd_options: -j -U "test@test.com" -n .zap/zap.context
