name: ZAP for Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t web-app . && docker run -dp 3000:3000 web-app
    - name: Create test user
      run: |
        sleep 10; 
        curl -i -s -k -X $'POST' \
          -H $'Host: localhost:3000' -H $'Content-Length: 234' -H $'sec-ch-ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"104\"' -H $'Accept: application/json, text/plain, */*' -H $'Content-Type: application/json' -H $'X-User-Email: test@test.com' -H $'sec-ch-ua-mobile: ?0' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36' -H $'sec-ch-ua-platform: \"macOS\"' -H $'Origin: http://localhost:3000' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Dest: empty' -H $'Referer: http://localhost:3000/' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' -H $'Connection: close' \
          -b $'language=en; welcomebanner_status=dismiss; cookieconsent_status=dismiss; continueCode=E3OzQenePWoj4zk293aRX8KbBNYEAo9GL5qO1ZDwp6JyVxgQMmrlv7npKLVy' \
          --data-binary $'{\"email\":\"test@test.com\",\"password\":\"test1\",\"passwordRepeat\":\"test1\",\"securityQuestion\":{\"id\":2,\"question\":\"Mother\'s maiden name?\",\"createdAt\":\"2022-11-12T14:49:19.846Z\",\"updatedAt\":\"2022-11-12T14:49:19.846Z\"},\"securityAnswer\":\"test\"}' \
          $'http://localhost:3000/api/Users/'
    - name: Get bearer token
      run: |
        ZAP_AUTH_HEADER_VALUE="Bearer "$(curl -X $'POST' \
          -H $'Host: localhost:3000' -H $'Content-Length: 44' -H $'sec-ch-ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"104\"' -H $'Accept: application/json, text/plain, */*' -H $'Content-Type: application/json' -H $'X-User-Email: test@test.com' -H $'sec-ch-ua-mobile: ?0' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36' -H $'sec-ch-ua-platform: \"macOS\"' -H $'Origin: http://localhost:3000' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Dest: empty' -H $'Referer: http://localhost:3000/' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' -H $'Connection: close' \
          -b $'language=en; welcomebanner_status=dismiss; cookieconsent_status=dismiss; continueCode=E3OzQenePWoj4zk293aRX8KbBNYEAo9GL5qO1ZDwp6JyVxgQMmrlv7npKLVy' \
          --data-binary $'{\"email\":\"test@test.com\",\"password\":\"test1\"}' \
          $'http://localhost:3000/rest/user/login' | jq -r '.authentication.token')
    - name: Export vars
      run: ZAP_AUTH_HEADER="Authorization" && export ZAP_AUTH_HEADER && export ZAP_AUTH_HEADER_VALUE
    - name: Print vars
      run: echo "$ZAP_AUTH_HEADER_VALUE"
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:3000'
        cmd_options: -z " \
          -config replacer.full_list\\(0\\).description=auth1 \  
          -config replacer.full_list\\(0\\).enabled=true \  
          -config replacer.full_list\\(0\\).matchtype=REQ_HEADER \  
          -config replacer.full_list\\(0\\).matchstr=Authorization \  
          -config replacer.full_list\\(0\\).regex=false \  
          -config replacer.full_list\\(0\\).replacement=$ZAP_AUTH_HEADER_VALUE "
